spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  application:
    name: emp-train
  # 数据库链接设置
  datasource:
    url: jdbc:mysql://${et.datasource.host}:${et.datasource.port}/${et.datasource.database}
    username: ${et.datasource.username}
    password: ${et.datasource.password}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    redis:
      host: ${et.redis.host}
      port: ${et.redis.port}
      database: ${et.redis.database}
      lettuce:
        pool:
          max-active: 10  # 最大连接数
          max-idle: 10    # 最大空闲连接
          min-idle: 1     # 最小空闲连接


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jaaaain.entity

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: jaaain-test02
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}

chat:
  proxy-host: 127.0.0.1
  proxy-port: 10809
  openai-key:  # 设置openai的key
  model: gpt-4
  temperature: 0.7

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug